set_property BITSTREAM.STARTUP.STARTUPCLK JTAGCLK [current_design]
set_property PACKAGE_PIN T18 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property PACKAGE_PIN T17 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property PACKAGE_PIN U17 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
set_property PACKAGE_PIN W19 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property PACKAGE_PIN U16 [get_ports {z1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z1[0]}]
set_property PACKAGE_PIN V14 [get_ports {z1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {z1[1]}]
set_property PACKAGE_PIN W5 [get_ports {CLK1}]
set_property IOSTANDARD LVCMOS33 [get_ports {CLK1}]
set_property PACKAGE_PIN V17 [get_ports {CLR1}]
set_property IOSTANDARD LVCMOS33 [get_ports {CLR1}]
